<a href="https://colab.research.google.com/github/MGrgat1/deep_learning_in_google_colab/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Torch and cuda

In [ ]:
import torch
import numpy
import matplotlib.pyplot as plt

print("Torch, version:")
print(torch.__version__)
print("Cuda enabled:")
print(torch.cuda.is_available())




Torch, version:
1.10.0+cu111
Cuda enabled:
True
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Tensor multiplication on the CPU (not using CUDA)


In [ ]:
print("Is A on cuda:")
print(a.is_cuda)
print("Is B on cuda:")
print(b.is_cuda)

a = torch.randint(0, 10, (3,3), dtype=torch.int)
print("A:")
print(a)
b = torch.randint(0, 10, (3,3), dtype=torch.int)
print("B:")
print(b)

print("A*B:")
print(a.mul(b))


A:
tensor([[2, 5, 2],
        [9, 6, 2],
        [8, 7, 7]], dtype=torch.int32)
B:
tensor([[4, 2, 3],
        [7, 3, 7],
        [6, 4, 1]], dtype=torch.int32)
A*B:
tensor([[ 8, 10,  6],
        [63, 18, 14],
        [48, 28,  7]], dtype=torch.int32)
Is A on cuda:
False
Is B on cuda:
False


Tensor multiplication on the GPU


In [ ]:
dev = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

a = torch.randint(0, 10, (3,3), device=dev, dtype=torch.int)
b = torch.randint(0, 10, (3,3), device=dev, dtype=torch.int)

print("A*B:")
print(a.mul(b))

print("Is A on cuda:")
print(a.is_cuda)
print("Is B on cuda:")
print(b.is_cuda)

A*B:
tensor([[15,  3, 36],
        [21, 15, 14],
        [21, 16,  5]], device='cuda:0', dtype=torch.int32)
Is A on cuda:
True
Is B on cuda:
True


Comparing CPU and GPU performance

In [ ]:
import time

a = torch.randint(0, 10, (4000,4000), dtype=torch.int)
b = torch.randint(0, 10, (4000,4000), dtype=torch.int)

startCPU = time.time()
for i in range(1000):
    c = a.mul(b)
endCPU = time.time()
print("CPU execution time:")
print(endCPU - startCPU)

a = a.cuda()
b = b.cuda()

startGPU = time.time()
for i in range(1000):
    c = a.mul(b)
endGPU = time.time()
print("GPU execution time:")
print(endGPU - startGPU)

CPU execution time:
19.11906623840332
GPU execution time:
0.0073850154876708984
